### ISSUE TITLE
Make the X and Y range values public global variables, so we can edit in inspector.

### ISSUE THREAD

**Issue by DisolveStudios** [DisolveStudios/DisFunction#7]
Make the X and Y range values public global variables, so we can edit in inspector.

_Originally posted by @DisolveStudios in https://github.com/DisolveStudios/DisFunction/pull/5#discussion_r1830643143_

**Comment by ruchithdhoni** [comment]
**X and Y can be changed in the Inspector now**
Closed the issue at the commit : https://github.com/DisolveStudios/DisFunction/commit/41da34ea3eecf32f56d792ed8fe93350883c9ec3

**Comment by ruchithdhoni** [comment]
### X and Y can be changed in the Inspector now
Closed the issue at the commit :https://github.com/DisolveStudios/DisFunction/commit/41da34ea3eecf32f56d792ed8fe93350883c9ec3
