### ISSUE TITLE
Game stuck on loading while on multiple dummy mode

### ISSUE THREAD

**Issue by AshishPhilip999** [DisolveStudios/DisFunction#8]
Single Mode is working fine but when you switch it to multiple dummy mode, it is not building. Should be a never ending loop error. Please check.

https://github.com/user-attachments/assets/6a404505-2b1c-4a4d-aa6e-a900ac0bd797

**Comment by ruchithdhoni** [comment]
Issue fixed here https://github.com/DisolveStudios/DisFunction/commit/b5f38b0163bac4fb20ca49b0d8a472020cadad26
